db: 
    driver: pdo_mysql
    name: phpbootcamp
    host: localhost
    username: root
    password: root
    
shipping_services: 
    - '\Bitwisdom\Shop\SPUShippingService'
    - '\Bitwisdom\Shop\ExFedShippingService'
